Add user methods
userfront/userfront-core pull request #12
Opened 2021-05-19 03:27 UTC by damionvega

2021-05-19 19:52 UTC, damionvega commented on src/index.js
> +}
Here is where `Userfront.store.user` is created.

- `...user` is the user information from the tokens
- `...apiResource` is what provides the `user.update` method
  The `afterUpdate` callback option was created in order to keep the `refresh` in one place and leave room to do other work if necessary.

2021-05-19 19:54 UTC, damionvega commented on src/index.js
> +  }
This can be modified/thrown away. Is only here to satisfy the current tests (`setCookiesAndTokens` needs to be called in order to update the tokens).

2021-05-19 20:00 UTC, damionvega commented on src/api-resource.js
> +  }
Currently `tenantId` and `accessToken` are required. If we decide to go forward with the `apiResource` design, I'd probably make another factory function e.g. `apiBase` (not sure of the name) that `apiResource` could adopt functionality from here and remove the need to pass those as options.

2021-05-19 20:26 UTC, tyrw commented
Can you clarify:
- As a project admin, how do I set a value?  E.g. `image` and `firstName`
- As a project admin, how do I read a value?  E.g. `image` and `firstName`

2021-05-19 20:48 UTC, damionvega commented
```js
const { user } = Userfront.store

// Read image value
user.image

// Read firstName value (is `undefined` if not present on `data` object in ID token)
user.firstName

// Update image and firstName
await user.update({
  image: 'https://example.com/profile-image.png',
  data: {
    firstName: 'Jane'
  }
})
```

- `user.updateImage` function can be added
- Updating attributes that require adding `data: { ... }` can be removed in order to allow for a flat object:
  ```js
  await user.update({
    image: 'https://example.com/updated.jpg',
    firstName: 'Jane',
  })
  ```
- If `user.firstName` is in popular demand and isn't set from the `data` object, perhaps we create a virtual property that returns the characters before before the first space in `user.name`.

2021-05-20 21:54 UTC, tyrw commented
From the chat:

Can you make this so the user doesn't care about implementation details:

```
await user.update({
  image: 'https://example.com/profile-image.png',
  data: {
    firstName: 'Jane'
  }
})
```

Should be

```
await user.update({
  image: 'https://example.com/profile-image.png',
  firstName: 'Jane'
})
```

As is, `user.firstName` doesn't make sense if they had to set it with `user.data.firstName`

It might be best to flatten data into the id token overall

E.g. the project admin would never need to know about `data`

2021-05-20 22:55 UTC, tyrw requested changes
The structure of the code seems to have a system to it, but it's hard to tell what you are going for.  I think this is partly due to lack of documentation about architecture or high-level API, partly due to confusing tests, and partly due to lack of smaller comments in tests.

- Please document somewhere what the syntax is
- The tests all reference `Userfront.store.user`, but you said it is `Userfront.user`. Can you write the tests to use that instead?
- This implementation doesn't seem to use the JWKS to verify the ID token. Am I missing it?
- It would be really nice if the tests were more descriptive of how things work, following a format more similar to our backend test suite: setup, action, assertion. E.g. a test might look look like:

```js
describe('user.update()', () => {
  before(() => {
    // Setup and mocks
  })
  it('should update a user', async () => {
    // Existing state
    expect(Userfront.user.image).toEqual('https://example.com/start.png')
    expect(Userfront.user.firstName).toBe(undefined)
    
    // Action
    const newImage = 'https://example.com/update.png'
    const newFirstName = 'Johnny'
    await Userfront.user.update({ 
      image: newImage,
      firstName: newFirstName
    })

    // Should have updated the user object
    expect(Userfront.user.image).toEqual(newImage)
    expect(Userfront.user.firstName).toEqual(newFirstName)

    // Should have updated the id token
    const idPayload = jwt.verify(Userfront.idToken(), publicKey)
    expect(idPayload.image).to.equal(newImage)
    expect(idPayload.firstName).to.equal(newFirstName)

    // Should have made the API request correctly
    ...
  })
})
```

2021-05-20 22:55 UTC, tyrw commented on src/user.js
> + */
The access token should not be needed for constructing the `user` object.  Looks like you are only using it for `authorization`, which we shouldn't commingle.

2021-05-20 23:00 UTC, tyrw commented
Also `api-resource.js` and "The `apiResource` design" both come across as very vague.  I read and re-read, and I still don't know what it's supposed to mean or reference.

2021-05-27 00:28 UTC, damionvega commented
I've added `verifyToken(token)` and `setUser()`. Since we currently have a single "model" we're working with, I decided to keep things simple and refactored the `apiResource`'s `update` function to the `user` factory and removed `api-resource.js`.

### verifyToken - public (`Userfront.verifyToken()`)
Primarily used to verify ID token before setting `Userfront.user`. Made available for admin to use if desired.
1. Decodes provided token
2. Fetches JWKS from `/jwks/{mode}`,
3. Gets public key from matching JWK
4. Verifies JWT with public key

### setUser - private
Called after `store.idToken` is set. Verifies the ID token and sets `store.user` for admin's use
of `Userfront.user`.
1. Verifies ID token via `verifyToken`
2. Assigns user object to `store.user` based on information in ID token and includes an `update` method to update user information

### Current API
```js
// Given example data:
{
  email: 'johndoe@example.com',
  username: 'johndoe',
  name: 'John Doe',
  image: 'https://example.com/profile-image.png',
  data: {
    country: 'Monoco',
  }
  // ...other properties
}

console.log(Userfront.user.name) // John Doe
console.log(Userfront.user.data.country) // Monoco

// Update user via Userfront API
await Userfront.user.update({
  username: "john-doe-updated",
  data: {
    country: "Spain",
  },
});

console.log(Userfront.user.username) // john-doe-updated
console.log(Userfront.user.data.country) // Spain
```

2021-06-01 17:44 UTC, tyrw requested changes
I updated the tests so that the `user` object is imported as it will be by others, rather than importing the `/src/user.js` file and testing on that.  This distinction is important, because it's how admins will use the package, so it needs to not be broken.

I made a note below about why it is broken, and it should be a straightforward fix, but I wanted to put it to you so that it clicks for future work.

2021-06-01 17:44 UTC, tyrw commented on src/index.js
> +  });
Assignment with `=` destroys any existing references to `user` that have been exported as

```js
const { user } = Userfront
```

2021-06-01 17:44 UTC, tyrw commented on test/user.spec.js
> +const { user } = Userfront;
Please import into all the tests like this, so that we are testing the way it will be used by the admins.

2021-06-02 01:22 UTC, tyrw commented
@damionvega the live version of this is available at https://mod.userfront.com/vtest, which means you can test it by replacing `/v3` in a snippet with `/vtest`, like so: 

```html
<script id="Userfront-script">
  (function(m,o,d,u,l,a,r,i,z,e) {
    u[m]={rq:[],ready:function(j){u[m].rq.push(j);},m:m,o:o,d:d,r:r};function j(s){return encodeURIComponent(btoa(s));}z=l.getElementById(m+"-"+a);r=u.location;
    e=[d+"/page/"+o+"/"+j(r.pathname)+"/"+j(r.host)+"?t="+Date.now(),d];e.map(function(w){i=l.createElement(a);i.defer=1;i.src=w;z.parentNode.insertBefore(i,z);});u.amvartem=m;
  })("Userfront", "p9ny8bdj", "https://mod.userfront.com/vtest",window,document,"script");
</script>
```

2 things to note:

- There are errors.  See console of https://codesandbox.io/s/recursing-grass-x4s46?file=/index.html for an example
- The bundle file is huge.  It went from 18kB without `jwks-rsa` to 287kB with it.  This is probably a deal breaker if there's no workaround.

2021-06-07 21:26 UTC, merged